name: flutter_code_generator
description: A sample command-line application.
version: 1.0.0

executables:
  generator:

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
